# Generated by Django 4.2.7 on 2023-11-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_maincontent_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincontent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
