# Generated by Django 4.2.7 on 2023-11-11 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_maincontent_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincontent',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
